// ? The forecast API is very limited, so it won't take long to reach 429 (Too Many Re'1' To simplify
// ? the development process, this array of mock data is used to simulate the API response.
export const mockData = {
  forecast: [
    {
      id: '1',
      valid_date: '2/11/2024',
      weather: 'Overcast clouds',
      u_date: 'Feb 11',
      u_max_temp: 8.1,
      u_min_temp: 3.3,
      max_temp: '8.1° C',
      min_temp: '3.3° C',
      moon_phase_description: 'New Moon',
      moon_phase_icon: '🌑',
    },
    {
      id: '2',
      valid_date: '2/12/2024',
      weather: 'Mix snow/rain',
      u_date: 'Feb 12',
      u_max_temp: 6.9,
      u_min_temp: 0.8,
      max_temp: '6.9° C',
      min_temp: '0.8° C',
      moon_phase_description: 'New Moon',
      moon_phase_icon: '🌑',
    },
    {
      id: '3',
      valid_date: '2/13/2024',
      weather: 'Few clouds',
      u_date: 'Feb 13',
      u_max_temp: 2.1,
      u_min_temp: -1.3,
      max_temp: '2.1° C',
      min_temp: '-1.3° C',
      moon_phase_description: 'New Moon',
      moon_phase_icon: '🌑',
    },
    {
      id: '4',
      valid_date: '2/14/2024',
      weather: 'Broken clouds',
      u_date: 'Feb 14',
      u_max_temp: 5.4,
      u_min_temp: -2.9,
      max_temp: '5.4° C',
      min_temp: '-2.9° C',
      moon_phase_description: 'New Moon',
      moon_phase_icon: '🌑',
    },
    {
      id: '5',
      valid_date: '2/15/2024',
      weather: 'Scattered clouds',
      u_date: 'Feb 15',
      u_max_temp: 5.8,
      u_min_temp: 0.2,
      max_temp: '5.8° C',
      min_temp: '0.2° C',
      moon_phase_description: 'New Moon',
      moon_phase_icon: '🌑',
    },
    {
      id: '6',
      valid_date: '2/16/2024',
      weather: 'Mix snow/rain',
      u_date: 'Feb 16',
      u_max_temp: 2.1,
      u_min_temp: -1.3,
      max_temp: '2.1° C',
      min_temp: '-1.3° C',
      moon_phase_description: 'First Quarter',
      moon_phase_icon: '🌓',
    },
    {
      id: '7',
      valid_date: '2/17/2024',
      weather: 'Few clouds',
      u_date: 'Feb 17',
      u_max_temp: 1.8,
      u_min_temp: -3.3,
      max_temp: '1.8° C',
      min_temp: '-3.3° C',
      moon_phase_description: 'First Quarter',
      moon_phase_icon: '🌓',
    },
  ],
  city_name: 'New York',
  state_code: 'NY',
  country_code: 'US',
};
